### ISSUE TITLE
Erro de sintaxe dependência python storm

### ISSUE THREAD

**Issue by samosaara** [stoq/stoq#15]
Eu estava tentando fazer o projeto rodar local na minha maquina local, mas não consegui passar da instalação de dependências, de acordo com as instruções eu simplesmente rodei o script de setup.py as-is com install, e o script funciona normal ate a parte de instalar uma biblioteca chamada `storm` , que pelo o que eu pude encontrar na internet era um ORM da canonical, mas ele e muito antigo, ele esta dando erro de sintaxe e compilação no próprio arquivo `setup.py` da biblioteca aqui no meu ambiente local com Arch Linux e Python 3.7.

Mas aparentemente a storm nunca foi atualizada pra python 3 também, o erro de sintaxe era numa sintaxe antiga de catch de múltiplas exceções que funcionava no python 2... Mas eu inclusive tentei rodar o setup.py do python2.7 para ver se esse projeto usava python 2 mas ai a versão do weasy print nao funciona mais no python2

Log da instalação https://gist.github.com/samosaara/8525e9544a051d877313ba1e274b8a26

**Comment by bellini666** [comment]
@samosaara o release oficial do storm não é compatível com python3, porém, você pode instalar o mesmo deste fork que foi criado por mim na época mas nunca foi mergeado upstream: https://code.launchpad.net/~bellini666/storm/py3

Caso esteja usando uma distribuição baseada em debian (com apt), você pode instalar o pacote (gerado deste fork) direto deste ppa: https://launchpad.net/~stoq-dev/+archive/ubuntu/lancamentos

cc @romaia

**Comment by samosaara** [comment]
Opa, muito obrigado pela resposta rápida. Consegui instalar o storm no meu ambiente local a partir do seu fork, mas depois disso, quando tentei executar o stoq ele pediu uma outra dependência que eu imagino que seja de runtime, o `pywebkitgtk` mas só que esse também eu só achei versão para o python 2... vocês tem um fork desse projeto adaptado pra python 3 também?

**Comment by bellini666** [comment]
@samosaara algumas dependências são gtk3 e vem de instrospection do gobject agora, e por isso não são instalaveis por pip.

Nestes casos, você pode instalar essas dependências do sistema. Neste caso por exemplo, em distros baseadas em debian (e.g. ubuntu) você pode instalar através desta dependência: `gir1.2-webkit-3.0`

Normalmente essas dependências vão começar com `gir1.2`, e.g. `gir1.2-gudev-1.0` para o gudev caso acuse estar faltando e assim por diante.

**Comment by samosaara** [comment]
Acho que eu me expressei errado não é isso que eu quiz dizer, o webkit gtk em si eu consegui instalar na minha máquina local, a biblioteca python especificamente, a biblioteca pywebkitgtk em si não é compilável para python3, depois de instalar o web kit gtk na minha maquina quando eu tento compilar para python 3 da uns erros de compilação nas bindings nativas, melhor, nem mesmo o script de configuração funciona no python 3 segue [logs do script com o python3](https://gist.github.com/samosaara/8525e9544a051d877313ba1e274b8a26#file-configure_pywebkitgtk_python3-txt) e [logs do script no python2](https://gist.github.com/samosaara/8525e9544a051d877313ba1e274b8a26#file-configure_pywebkitgtk_python2-txt)

Eu inclusive tentei usar o pywebkitgtk que eu tirei do PPA de vocês na esperança de vocês terem feito alguma adaptação... Mas assim, na pior das hipóteses, só pra eu entender, com esse pacote .deb vocês conseguem instalar o webkitgtk pra python3, e dar `import webkit` no python 3.7?

**Comment by samosaara** [comment]
Eu fiz a coisa mais obvia e tudo fez sentido, simplesmente tentei achar o código de validação dessa dependência e vi que na verdade ela não estava checando por pywebkitgtk coisa nenhuma e sim as bindings de GTK WebKit 3 do pygoobject, e nem usa mais o pywebkitgtk. Instalei-as e funcionou.

Daí vi que as dependências `requests` e `futures` estavam faltando do `requirements.txt`, mas já foram adicionadas e também que foi colocado o link direto pra um tar do storm ao invés da versão do PyPi, mas esse tar ainda é o da versão 2... De qualquer forma, consegui usar o storm do seu branch para subir a aplicação.

Depois que estava funcionando tive uns problemas com o meu postgresql, usuário, permissões, mas aí acho fora do escopo desse issue.

**TL;DR**: a dependência `storm` realmente está depreciada e o projeto tem um fork pro python 3, a dep. pywebkitgtk estava lá erroneamente e mensagem está errada o que usa agora é o pyGObject direto com bindings pra webkit
