### ISSUE TITLE
Dispositivos SAT disponiveis

### ISSUE THREAD

**Issue by xmnlab** [stoq/stoq#21]
estimadas e estimados,

encontrei essa lista de impressoras SAT disponiveis: https://async.freshdesk.com/support/solutions/articles/4000102500-sat

como essa lista é antiga, gostaria de saber se mais impressoras são suportadas atualmente ou se essa lista é a mais atualizada.

agradecido pela atenção.

**Comment by luisoishi** [comment]
Caro Ivan,

No seu texto você mencionou 'impressora SAT', mas acredito que esteja se referindo ao equipamento SAT.
 
Quanto aos dispositivos SAT, não houve nenhuma atualização nos equipamentos SAT suportados.

Caso eu tenha entendido seu questionamento de maneira equivocada, por favor me avise.

**Comment by xmnlab** [comment]
exatamente, desculpe a confusão ... muito obrigado @luisoishi pelas informações!
