### ISSUE TITLE
Integração com o menu global do Ubuntu

### ISSUE THREAD

**Issue by rauldipeas** [stoq/stoq#5]
Há alguma forma de integrar o menu do Stoq com o menu global do Ubuntu 15.04/15.10?(aquele no topo da tela)

Eu tentei instalar alguns pacotes adicionais de suporte, mas nenhum surtiu efeito:

unity-gtk2-module
unity-gtk2-module:i386
unity-gtk3-module
unity-gtk3-module:i386
appmenu-qt
appmenu-qt:i386
appmenu-qt5
appmenu-qt5:i386(esse remove a versão x64)

**Comment by hackedbellini** [comment]
@rauldipeas a integração já funciona, mas [nós desativamos a mesma propositalmente](https://github.com/stoq/stoq/blob/master/bin/stoq#L59) pois ela quebrava alguns menus dinâmicos.

Aproveitando, quando for fazer alguma pergunta em relação ao software, de preferência tente utilizar a [lista de emails stoq-users](http://www.async.com.br/mailman/listinfo/stoq-users)

**Comment by rauldipeas** [comment]
Obrigado pela resposta, vou usar a lista de emails na próxima!
