### ISSUE TITLE
Pacote para o Arch Linux e derivados

### ISSUE THREAD

**Issue by neton-bricio** [stoq/stoq#6]
Olá pessoal, conheci o Stoq atravé de uma amigo, gostei do programa. Porém só encontrei o mesmo no repositório do Ubuntu e Slitaz.

Há possibilidade de criar pacotes para o Arch e disponibizar no AUR?

**Comment by romaia** [comment]
Olá @neton-bricio 

Infelizmente nossa equipe é pequena e não temos como oferecer suporte para outras distribuições que não seja ubuntu.

Há pacotes não oficiais para outras distribuições, e se não houver para Arch, você ainda pode instalar o stoq usando o pip

**Comment by Henrique-Miranda** [comment]
@romaia  Infelismente instalar o Stoq pelo pip não funciona, pelo que pesquisei o Arch usa python 3 como padrão. Gostaria muito de usar o Stoq no Manjaro (distro baseada no Arch que uso atualmente), se caso "pintar" um tempinho vocês poderiam porta-lo para o Arch :) . Os usuarios Arch e Manjaro estão aumentando muito e seria uma boa para a divulgação do orgulhoso software brasileiro Stoq.

**Comment by snydermacedo** [comment]
Olá pessoal, gostaria de sabe o podeira ser feito ajudar a portabilidade.
Desde já agradeço.

**Comment by neton-bricio** [comment]
Poderiam pelo menos oferecer binários executáveis. Já seria um bom começo

**Comment by hackedbellini** [comment]
@neton-bricio você pode baixar os "binários" das seguintes formas:

1) Baixando o arquivo tar.gz do pypi: https://pypi.python.org/pypi/stoq
2) Direto do [código fonte](https://wiki.stoq.com.br/index.php/Come%c3%a7ando) utilizando o commando `python setp.py sdist`

**Comment by neton-bricio** [comment]
Valeu. Funciona muito bem no Manjaro, Arch e Void Linux. Testado e parovado

**Comment by snydermacedo** [comment]
Neton, olá.

Testei aqui mas não conseguir, qual procedimento você usou?

**Comment by snydermacedo** [comment]
Olá Neton bom dia.

Tentei instalar no Manjaro mais não tive sucesso.
Qual o procedimento que você usou.

Desde já agradeço.


Em 18-08-2016 21:02, Neton Brício escreveu:

**Comment by Henrique-Miranda** [comment]
Também não consegui, alguem pode fazer uma boa ação explicando o procedimento correto?
