### ISSUE TITLE
Exportar lista relatorio de vendas com fornecedores

### ISSUE THREAD

**Issue by romulomourao** [stoq/stoq#7]
Tem alguma forma de exportar o relatorio de vendas pra planilha com uma coluna de fornecedores além do que já aparece normalmente?

**Comment by romaia** [comment]
olá @romulomourao .

Isso é um pouco complicado para implementarmos pois um produto pode ser fornecido por diversos fornecedores diferentes.

Entendemos que muitas vezes o único fornecedor de um produto é o próprio fabricante, ou uma empresa não trabalha com mais de um fornecedor para aquele produto, mas o que recomendamos nesse caso é preencher também a informação do fabricante no cadastro do produto e extrair o relatório baseado nessa informação.
