### ISSUE TITLE
IOCregex whitelist behavior

### ISSUE THREAD

**Issue by redlazarus** [stoq/stoq#8]
IOCregex reader plugin has a whitelist that differentiates between domain and url types.  In most use cases, these lists are likely identical and easier to maintain as a single list. 

Suggest merging the two into a single whitelist indicator type (recommend domain).  

For additional flexibility, allow for type exception cases for either domain or url regex extraction.  I
i.e., if .cnn.com is added to the whitelist, allow for an additional indicator type that excludes the whitelist entry from either url or domain matches. 

i.e. 
domain:.cnn.com 
excepturl:.cnn.com

The above example would not include cnn.com to the url indicator type whitelist, but it would remain for the domain type.

**Comment by romaia** [comment]
I think you have the wrong project for this issue report.
