### ISSUE TITLE
Banco de dados faltando 5 novas cidades

### ISSUE THREAD

**Issue by Montanheiro** [stoq/stoq#9]
Estava olhando o banco de dados para conhecer o sistema e notei que tem 5565 cidades cadastradas e a partir de 2013 foram inseridas mais 5 cidades, num total de 5570 cidades brasileiras.

Fonte: [Com 5 novos municípios, Brasil agora tem 5.570 cidades - O Globo](http://oglobo.globo.com/brasil/com-5-novos-municipios-brasil-agora-tem-5570-cidades-7235803)

**Comment by maigheo** [comment]
Cool Story Bro !

**Comment by Montanheiro** [comment]
#10
